environment:
  matrix:
    - PYTHON: "C:\\Python27"
      MINGW: "mingw32"
    - PYTHON: "C:\\Python27-x64"
      MINGW: "mingw64"
    - PYTHON: "C:\\Python33"
      MINGW: "mingw32"
    - PYTHON: "C:\\Python33-x64"
      MINGW: "mingw64"
    - PYTHON: "C:\\Python34"
      MINGW: "mingw32"
    - PYTHON: "C:\\Python34-x64"
      MINGW: "mingw64"
    - PYTHON: "C:\\Python35"
      MINGW: "mingw32"
    - PYTHON: "C:\\Python35-x64"
      MINGW: "mingw64"
    - PYTHON: "C:\\Python36"
      MINGW: "mingw32"
    - PYTHON: "C:\\Python36-x64"
      MINGW: "mingw64"

#platform:
#  - x86
  #- x64

#matrix:
#  fast_finish: true

clone_depth: 3

init:
  - ECHO %PYTHON%

install:
  # Use correct gcc compiler
  - "SET PATH=C:\\msys64\\%MINGW%\\bin;%PATH%" 
  # tox for testing
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - "python -m pip install tox"
  # We need wheel installed to build wheels
  - "python -m pip install --upgrade wheel"
  
build: off
  
test_script:
  - "tox -e py"
  
after_test:
  - "python setup.py bdist_wheel"

artifacts:
  - path: dist\*
